### ISSUE TITLE
使用autoupload.sh中的配置移动至GoogleDrive时会上传下载目录

### ISSUE THREAD

**Issue by bh6kag** [P3TERX/aria2_perfect_config#3]
downloadpath='/data/Download/' #Aria2下载目录
name='test' #配置Rclone时填写的name
folder='/share' #网盘里的文件夹，留空为整个网盘。
如设置以上参数后，下载的文件会上传整个下载目录
如GD上实际上传目录是： share/new folder/data/download

**Comment by P3TERX** [comment]
`downloadpath='/data/Download'` 去掉最后的斜杠
