### ISSUE TITLE
bt下载没有触发自动上传

### ISSUE THREAD

**Issue by lhiqwj173** [P3TERX/aria2_perfect_config#4]
测试网盘转存可以自动上传，bt下载的文件没有触发
如下
[1;35mDownload path：[0m/root/Download
[1;35mFile path: [0m/root/Download/Game.of.Thrones.S08E01.WEBRip.x264-ION10/Game.of.Thrones.S08E01.WEBRip.x264-ION10.mp4
[1;35mUpload path: [0m
[1;35m.aria2 file path: [0m
[1;35mRemote path：[0m

**Comment by P3TERX** [comment]
感谢反馈，最新脚本已经修复这个问题。
