### ISSUE TITLE
多个网盘上传问题

### ISSUE THREAD

**Issue by sixgodjuice** [P3TERX/aria2_perfect_config#6]
很感谢大佬分析的教程，安装成功，上传暂时也没有问题，但本人有几个onedrive，想实现aria2下载到不同的目录，文件通过rclone上传到不同网盘。
比如：
aira2下载到/home/A,自动上传到A网盘；
aira2下载到/home/B,自动上传到B网盘；
我根据您的上传代码修改了一下，发现用不了，小白一枚，所以能不能帮忙修改下代码，谢谢

**Comment by P3TERX** [comment]
你这个想法很不错，但是如果要实现可能需要重写脚本了。这个牵扯到很多复杂的路径判断的逻辑，现有的路径判断逻辑是基于已有的下载路径上的。在不改动代码的情况下实现你这个想法其实只需要另外运行一个 Aria2 就可以了。

**Comment by catwa1k** [comment]
> 你这个想法很不错，但是如果要实现可能需要重写脚本了。这个牵扯到很多复杂的路径判断的逻辑，现有的路径判断逻辑是基于现有的下载路径上的。在不放置代码的情况下下实现你这个想法其实只需要另外运行一个Aria2就可以了。

大佬，同样需求，你说的 只需另外运行一个Aria2就可以了。具体是怎么操作的，小白不懂，请教 谢谢
