### ISSUE TITLE
[反馈一个问题]如果文件任务暂停，再删除任务就无法删除文件

### ISSUE THREAD

**Issue by SuperNG6** [P3TERX/aria2_perfect_config#7]
如题，直接删除任务是可以删除文件的，但是如果先暂停再删除任务就无法删除文件

**Comment by P3TERX** [comment]
Aria2 的问题。从暂停状态删除任务不会触发 `on-download-stop`这个选项，所以删除脚本也就不会运行，文件也就不会被删除。

**Comment by SuperNG6** [comment]
感谢解答

P3TERX <notifications@github.com>于2019年7月22日 周一下午7:19写道：
