### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by usbcdrom** [P3TERX/aria2_perfect_config#9]
我使用了你的一键完美配置aria2，体验是很棒的，但是我想使aria2下载到本地virtualvbox虚拟机centos7挂载的usb移动硬盘目录,通过设置下载目录为移动硬盘，但是只要任务开始立即就出错了，感觉是不可写入一样，因为桌面环境下是可是正常读写的，应该挂载是没问题的，然后我就想到能不能下载到centos本地然后再转移到移动硬盘，然后我网上搜到了这样一个脚本，下载完成后转移是成功的，但新问题又出现了，就是在aria2.conf最后一行加入后，你的脚本自动删除.aria2后缀文件不起作用了，.aria2留在了下载目录，下载文件转移是成功的。
请教：不能直接下载到挂载的移动硬盘和添加转移脚本后不能删除.aria2文件是哪里出了问题，或者同学能不能把自动转移功能添加进去

这个是我网上搜的
**_Aria2下载完成后转移文件到指定目录_**
2019-04-04 03:43  阅读 1,155 views 次 
这个脚本的作用就是再aria2下载完文件后将文件转移到其它目录的自动处理脚本；

编辑aria2.conf文件，增加以下代码
#我添加在配置文件最后一行
on-download-complete=/root/.aria2/move.sh
move.sh脚本内容如下
#!/bin/sh
 
# $1 is gid.
# $2 is the number of files.
# $3 is the path of the first file.
 
DOWNLOAD=/tmp # aria2的下载目录
COMPLETE=/home/down # 你要设置的转移目录路径
LOG=/root/.aria2/mvcompleted.log  #脚本操作日志
SRC=$3
 
if [ "$2" == "0" ]; then
  echo `date` "INFO  no file to move for" "$1". >> "$LOG"
  exit 0
fi
 
while true; do
  DIR=`dirname "$SRC"`
  if [ "$DIR" == "$DOWNLOAD" ]; then
    echo `date` "INFO " "$3" moved as "$SRC". >> "$LOG"
    mv --backup=t "$SRC" "$COMPLETE" >> "$LOG" 2>&1
    exit $?
  elif [ "$DIR" == "/" -o "$DIR" == "." ]; then
    echo `date` ERROR "$3" not under "$DOWNLOAD". >> "$LOG"
    exit 1
  else
    SRC=$DIR
  fi
done

**Comment by P3TERX** [comment]
1. “不能直接下载到挂载的移动硬盘”这个问题可能是文件预分配的方式不适用这个硬盘的格式，你可以c尝试去修改配置文件的第40行`file-allocation`参数，上面有说明。
2. “添加转移脚本后不能删除.aria2文件”是因为这个脚本没有这个功能。删除`.aria2`文件的功能是写在我的脚本中的。

**Comment by usbcdrom** [comment]
> 1. “不能直接下载到挂载的移动硬盘”这个问题可能是文件预分配的方式不适用这个硬盘的格式，你可以尝试去修改配置文件的第40行`file-allocation`参数，上面有说明。
> 2. “添加转移脚本后不能删除.aria2文件”是因为这个脚本没有这个功能。删除`.aria2`文件的功能是写在我的脚本中的。
我的USB移动硬盘是NTFS格式，40行默认参数是推荐NTFS格式的@#@……

**Comment by usbcdrom** [comment]
同学我通过查阅问题已经解决了，问题应该出在了内核不支持这里，虽然我的centos7是最新版，但是你的一键安装aria2不是编译安装，这里改成这样就解决不能下载到NTFS分区的问题了
![QQ截图20190809150611](https://user-images.githubusercontent.com/43695445/62760926-d497a400-bab7-11e9-83d6-d9be19058693.jpg)

**Comment by P3TERX** [comment]
刚准备跟你说改成`none`，不过都一样。解决了就行。
